package com.seaglassfoundry.swingtopdf.demo;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import com.seaglassfoundry.swingtopdf.SwingPdfExporter;
import com.seaglassfoundry.swingtopdf.api.ExportMode;
import com.seaglassfoundry.swingtopdf.api.PageSize;

import java.awt.*;
import java.awt.Desktop;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.concurrent.CountDownLatch;

/**
 * Generates a multi-page PDF from a tall panel containing a large JTable
 * and stacked content sections.
 *
 * <p>Run with:
 * <pre>
 *   mvn test-compile exec:java \
 *     -Dexec.mainClass=com.seaglassfoundry.swingtopdf.demo.GenerateLongPanelPdf \
 *     -Dexec.classpathScope=test
 * </pre>
 */
public class GenerateLongPanelPdf {

    private static final int PANEL_W = 800;

    public static void main(String[] args) throws Exception {
        Path out = Paths.get("swingtopdf-longpanel-output.pdf").toAbsolutePath();

        JPanel[] holder = new JPanel[1];
        CountDownLatch latch = new CountDownLatch(1);
        SwingUtilities.invokeLater(() -> {
            holder[0] = buildPanel();
            // Let preferred height drive layout; set a fixed width
            holder[0].setSize(PANEL_W, holder[0].getPreferredSize().height);
            holder[0].validate();
            latch.countDown();
        });
        latch.await();

        System.out.println("Panel height: " + holder[0].getHeight() + " px");
        System.out.println("Exporting to: " + out);

        SwingPdfExporter.from(holder[0])
                .pageSize(PageSize.A4)
                .exportMode(ExportMode.DATA_REPORT)
                .margins(28, 28, 28, 28)
                .export(out);

        System.out.println("Done.");

        if (Desktop.isDesktopSupported()) {
            Desktop.getDesktop().open(out.toFile());
        }
    }

    private static JPanel buildPanel() {
        JPanel root = new JPanel();
        root.setLayout(new BoxLayout(root, BoxLayout.Y_AXIS));
        root.setBackground(Color.WHITE);
        root.setBorder(BorderFactory.createEmptyBorder(16, 16, 16, 16));

        // Title
        JLabel title = new JLabel("Long Panel — Pagination Test");
        title.setFont(title.getFont().deriveFont(Font.BOLD, 22f));
        title.setAlignmentX(Component.LEFT_ALIGNMENT);
        root.add(title);
        root.add(vgap(12));

        // Description
        JTextArea desc = new JTextArea(
            "This document tests multi-page pagination with a 50-row table " +
            "followed by additional content sections. Page breaks should not " +
            "bisect table rows.", 3, 60);
        desc.setLineWrap(true);
        desc.setWrapStyleWord(true);
        desc.setEditable(false);
        desc.setBackground(new Color(0xF5F5F5));
        desc.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(0xCCCCCC)),
            BorderFactory.createEmptyBorder(6, 8, 6, 8)));
        desc.setAlignmentX(Component.LEFT_ALIGNMENT);
        root.add(desc);
        root.add(vgap(16));

        // Large table
        root.add(sectionHeader("Employee Directory (50 rows)"));
        root.add(vgap(4));
        root.add(buildTable());
        root.add(vgap(20));

        // Summary stats section
        root.add(sectionHeader("Department Summary"));
        root.add(vgap(4));
        root.add(buildSummaryTable());
        root.add(vgap(20));

        // Notes section
        root.add(sectionHeader("Notes"));
        root.add(vgap(4));
        JTextArea notes = new JTextArea(
            "1. All salary figures are annual gross in USD.\n" +
            "2. Department codes: ENG = Engineering, MKT = Marketing, " +
            "FIN = Finance, HR = Human Resources, OPS = Operations.\n" +
            "3. Data is for illustration purposes only.\n" +
            "4. Report generated by SwingVecPDF.", 6, 60);
        notes.setLineWrap(true);
        notes.setWrapStyleWord(true);
        notes.setEditable(false);
        notes.setAlignmentX(Component.LEFT_ALIGNMENT);
        root.add(notes);
        root.add(vgap(16));

        return root;
    }

    private static JScrollPane buildTable() {
        String[] cols = {"#", "Name", "Department", "Title", "Location", "Salary"};
        String[] depts   = {"ENG", "MKT", "FIN", "HR", "OPS"};
        String[] titles  = {"Engineer", "Manager", "Analyst", "Director", "Specialist"};
        String[] locs    = {"New York", "London", "Tokyo", "Sydney", "Berlin"};
        String[] firstNames = {"Alice","Bob","Carol","David","Eva","Frank","Grace",
                               "Henry","Iris","James","Karen","Leo","Mia","Noah",
                               "Olivia","Paul","Quinn","Rachel","Sam","Tara"};
        String[] lastNames  = {"Smith","Jones","Williams","Brown","Davis","Miller",
                               "Wilson","Moore","Taylor","Anderson","Thomas","Jackson",
                               "White","Harris","Martin","Garcia","Martinez","Lee","Clark","Lewis"};

        Object[][] rows = new Object[50][6];
        for (int i = 0; i < 50; i++) {
            rows[i][0] = i + 1;
            rows[i][1] = firstNames[i % firstNames.length] + " " + lastNames[i % lastNames.length];
            rows[i][2] = depts[i % depts.length];
            rows[i][3] = titles[i % titles.length];
            rows[i][4] = locs[i % locs.length];
            rows[i][5] = String.format("$%,d", 60_000 + (i * 1_847) % 90_000);
        }

        JTable table = new JTable(new DefaultTableModel(rows, cols) {
            private static final long serialVersionUID = -8923662611707791627L;

			@Override public boolean isCellEditable(int r, int c) { return false; }
        });
        table.setRowHeight(22);
        table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.getColumnModel().getColumn(0).setPreferredWidth(30);
        table.getColumnModel().getColumn(1).setPreferredWidth(160);
        table.getColumnModel().getColumn(2).setPreferredWidth(60);
        table.getColumnModel().getColumn(3).setPreferredWidth(120);
        table.getColumnModel().getColumn(4).setPreferredWidth(90);
        table.getColumnModel().getColumn(5).setPreferredWidth(80);

        // Show all rows — no scroll clip
        int tableH = table.getRowCount() * table.getRowHeight()
                   + table.getTableHeader().getPreferredSize().height + 4;
        JScrollPane sp = new JScrollPane(table);
        sp.setPreferredSize(new Dimension(PANEL_W - 32, tableH));
        sp.setAlignmentX(Component.LEFT_ALIGNMENT);
        return sp;
    }

    private static JScrollPane buildSummaryTable() {
        String[] cols = {"Department", "Head Count", "Avg Salary", "Min Salary", "Max Salary"};
        Object[][] rows = {
            {"ENG", 10, "$112,450", "$68,000", "$148,000"},
            {"MKT",  8,  "$84,250", "$62,000", "$105,000"},
            {"FIN",  7,  "$97,800", "$71,000", "$130,000"},
            {"HR",   6,  "$76,300", "$58,000",  "$95,000"},
            {"OPS",  9,  "$88,500", "$63,000", "$118,000"},
        };
        JTable table = new JTable(new DefaultTableModel(rows, cols) {
            private static final long serialVersionUID = -7784150736885344702L;

			@Override public boolean isCellEditable(int r, int c) { return false; }
        });
        table.setRowHeight(22);
        table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        int tableH = table.getRowCount() * table.getRowHeight()
                   + table.getTableHeader().getPreferredSize().height + 4;
        JScrollPane sp = new JScrollPane(table);
        sp.setPreferredSize(new Dimension(PANEL_W - 32, tableH));
        sp.setAlignmentX(Component.LEFT_ALIGNMENT);
        return sp;
    }

    private static JPanel sectionHeader(String text) {
        JPanel p = new JPanel(new BorderLayout());
        p.setMaximumSize(new Dimension(Integer.MAX_VALUE, 28));
        p.setAlignmentX(Component.LEFT_ALIGNMENT);
        p.setBackground(new Color(0x2B4C7E));
        p.setOpaque(true);
        p.setBorder(BorderFactory.createEmptyBorder(4, 8, 4, 8));
        JLabel l = new JLabel(text);
        l.setFont(l.getFont().deriveFont(Font.BOLD, 13f));
        l.setForeground(Color.WHITE);
        p.add(l, BorderLayout.CENTER);
        return p;
    }

    private static Component vgap(int h) {
        return Box.createVerticalStrut(h);
    }
}
